version: '3'
#networks:
#	jira-network:
#volumes:
#jira-data:
services:
  jira:
#   build:
#    context: ./
    image: jira_f
    container_name: jira
    hostname: jira
    restart: unless-stopped
    ports: 
      - 8081:8080
 #   networks:
 #     - jira-network
    environment: 
      - JVM_SUPPORT_RECOMMENDED_ARGS='-verbose:gc -Dfile.encoding=UTF-8 -XX:+PrintGCDateStamps -XX:PrintGCTimeStamps -Xloggc:/var/atlassian/application-data/jira/log/jira-gc.log-`date +%Y%m%d%H%M%S`'
#      - JAVA_HOME=/opt/java/default/jre/
  postgreSQL:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    privileged: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jirauser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=jiradb
#    volumes:
      #- database_data:/var/lib/postgresql/data/pgdata